languageCode = "en-us"
title = "Project Indexly"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
enableGitInfo = false
pygmentsUseClasses = true
canonifyURLs = true
pagination.paperSize = 20

[params]
  copyright = "Project Indexly"
  author = "N.K. Franklin-Gent"
  footer = true
  description = "Indexly is a fast, offline local file search tool for Word, PDF, and text files. Built for researchers, academics, and power users."
  keywords = "local file search, Word document indexing, offline file search, academic research tool, SQLite FTS5, regex file search"
  favicon = "images/favicon.png"
  opengraphImage = "images/preview.png"
  github_repo = "https://github.com/kimsgent/project-indexly"
  showVisitedLinks = true
  themeVariant = "auto"

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser]
    autoHeadingID = true

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    vendored = true

  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = true # We copied the files manually, so this avoids loading the module

[languages.en]
  languageName = "English"
  weight = 1

  [[languages.en.menus.main]]
    identifier = "home"
    name = "Home"
    pre = "<i class='fa fa-heart'></i>"
    url = "/en/"
    weight = 1

  [[languages.en.menus.main]]
    name = "Documentation"
    pre = "<i class='fa fa-book'></i>"
    url = "/en/documentation/"
    weight = 3

  [[languages.en.menus.main]]
    name = "Download"
    pre = "<i class='fa fa-download'></i>"
    url = "/en/download/"
    weight = 4

  [[languages.en.menus.main]]
    name = "Contact"
    pre = "<i class='fa fa-envelope'></i>"
    url = "/en/contact/"
    weight = 6

